---

- name: Print out swarm info
  debug:
    msg:
      - "manager_group:{{ manager_group }}"
      - "advertise_address:{{ advertise_address }}"
      - "manager_node:{{ manager_node }}"
      - "manager_nodes:{{ manager_nodes }}"
      - "manager_token:{{ manager_token }}"
      - "worker_token:{{ worker_token }}"
      - "api_version:{{ docker.api_version }}"
#     - "WORKER: {{ hostvars[inventory_hostname] }}"



- name: Add worker
  docker_swarm:
    api_version: '{{ docker.api_version }}'
    state: join
    advertise_addr: "{{ advertise_address }}"
    join_token: "{{ worker_token }}"
    remote_addrs: "{{ manager_nodes }}"

