---

user_name: 'vagrant'


swarm_managers_group_name: 'swarm_managers'

network_published_port: 80
network_target_port: 3000


# dns server details
dns:
    zone_name: test.com
    ns_name: ns1
    ns_network: 192.168.100.0/24
    ns_adress: 192.168.100.10
    ns_adress_reverse: 10
    ns_adress_reverse2: 100.168.192
    ns_forwarders: 8.8.8.8

