---

- debug:
    msg:
      - 'prometheus_target:{{ prometheus_target }}'
      - 'port:{{ port }}'
      - 'job_name:{{ job_name }}'
      - 'groups:{{ groups }}'
      - 'groups.APP:{{ groups.APP }}'
      - 'ansible_hostname:{{ ansible_hostname }}'



# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#dns_sd_config
# https://www.innoq.com/en/blog/scraping-docker-swarm-service-instances-with-prometheus/
# https://groups.google.com/g/prometheus-users/c/vqbzS7WKjN0
# https://containers.goffinet.org/k8s/prometheus.html
# https://en.wikipedia.org/wiki/List_of_DNS_record_types
# https://kb.timescale.cloud/en/articles/3641695-connecting-prometheus-to-your-instance
- name: Append prometheus scrape targets(dynamic config)
  delegate_to: '{{ prometheus_target }}'
  blockinfile:
    path: /home/vagrant/d_service/prometheus/prometheus.yml
    marker: "# {mark} append {{ job_name }} to prometheus"
    block: |2
        - job_name: '{{ job_name }}'
          scrape_interval: 10s
          dns_sd_configs:
            - names:
              - '{{ ansible_hostname }}'
              type: 'A'
              port: {{ port }} 



####- name: Append prometheus scrape targets(static config)
####  delegate_to: '{{ prometheus_target }}'
####  blockinfile:
####    path: /home/vagrant/d_service/prometheus/prometheus.yml
####    marker: "# {mark} append {{ job_name }} to prometheus"
####    block: |2
####        - job_name: '{{ job_name }}'
####          scrape_interval: 10s
####          static_configs:
####            - targets: ['{{ ansible_hostname }}:{{ port }}']

