---

# https://portainer.readthedocs.io/en/stable/deployment.html#inside-a-swarm-cluster
# https://portainer.readthedocs.io/en/stable/agent.html
# https://www.portainer.io/2018/10/using-portainer-agent/

- name: Print out portainer info
  debug:
    msg:
     - "tag:{{ tag }}"
     - "src_port:{{ src_port }}"
     - "dst_port:{{ dst_port }}"
     - "network_name:{{ network_name }}"
     - "advertise_address:{{ advertise_address }}"
  tags: portainer



- name: Copy portainer deployment file
  template:
    src: 'portainer-stack.j2'
    dest: '/home/{{ user_name }}/portainer-stack.yml'
  tags: portainer



- name: Deploy portainer
  command: docker stack deploy --compose-file=/home/{{ user_name }}/portainer-stack.yml portainer
  tags: portainer

