---

#https://portainer.readthedocs.io/en/stable/deployment.html#inside-a-swarm-cluster
#https://portainer.readthedocs.io/en/stable/agent.html
#https://www.portainer.io/2018/10/using-portainer-agent/

- name: Print out portainer agent info
  debug:
    msg:
     - "tag: {{ portainer_agent.tag }}"
  tags: portainer_agent



- name: Copy portainer agent deployment file
  vars:
    tag: '{{ portainer_agent.tag }}'
  template:
    src: 'portainer-agent-stack.j2'
    dest: '/tmp/portainer-agent-stack.yml'
  tags: portainer_agent

 

- name: Deploy portainer agent
  command: docker stack deploy --compose-file=/tmp/portainer-agent-stack.yml portainer_agent
  tags: portainer_agent

