---

advertise_address: '192.168.200.10:2377'
manager_nodes: '{{ hostvars[inventory_hostname].groups[manager_group]}}'
manager_node:  '{{ hostvars[inventory_hostname].groups[manager_group][0]}}'
manager_token: '{{ hostvars[manager_node].swarm_info.swarm_facts.JoinTokens.Manager }}'
worker_token:  '{{ hostvars[manager_node].swarm_info.swarm_facts.JoinTokens.Worker }}'

