---

- debug:
    msg:
      - 'dockprom:{{ dockprom }}'
      - 'exporters:{{ exporters }}'
      - 'version:{{ version }}'



- name: Checkout repo
  git:
    repo: 'https://github.com/donDonald/dockprom.git'
    force: true
    dest: /home/{{ user_name }}/d_service
    version: '{{ version }}'
  tags: dockprom_service



- name: Deploy prometheus config
  template:
    src: prometheus/prometheus.yml
    dest: /home/{{ user_name }}/d_service/prometheus/prometheus.yml
  tags: dockprom_service



- name: Append prometheus scrape targets(dynamic config)
  vars:
    job_name: 'prometheus'
    exporters: '{{ dockprom }}'
    port: 9090
  blockinfile:
    path: /home/{{ user_name }}/d_service/prometheus/prometheus.yml
    marker: "# {mark} append {{ job_name }} to prometheus"
    block: "{{ lookup('template', 'prometheus/dns_sd_configs.j2') }}"
  tags: dockprom_service



- name: Append nodeexporter scrape targets(dynamic config)
  vars:
    job_name: 'nodeexporter'
    port: 9100
  blockinfile:
    path: /home/{{ user_name }}/d_service/prometheus/prometheus.yml
    marker: "# {mark} append {{ job_name }} to prometheus"
    block: "{{ lookup('template', 'prometheus/dns_sd_configs.j2') }}"
  tags: dockprom_service



- name: Append cadvisor scrape targets(dynamic config)
  vars:
    job_name: 'cadvisor'
    port: 8080
  blockinfile:
    path: /home/{{ user_name }}/d_service/prometheus/prometheus.yml
    marker: "# {mark} append {{ job_name }} to prometheus"
    block: "{{ lookup('template', 'prometheus/dns_sd_configs.j2') }}"
  tags: dockprom_service



- name: Deploy grafana config
  template:
    src: grafana/provisioning/datasources/datasource.yml
    dest: /home/{{ user_name }}/d_service/grafana/provisioning/datasources/datasource.yml
  tags: dockprom_service



- name: Append prometheus to grafana config
  vars:
    name: 'Prometheus'
    type: 'prometheus'
    source: '{{ dockprom }}'
    port: 9090
  blockinfile:
    path: /home/{{ user_name }}/d_service/grafana/provisioning/datasources/datasource.yml
    marker: "# {mark} append {{ name }} to grafana"
    block: "{{ lookup('template', 'grafana/provisioning/datasources/datasource.j2') }}"
  tags: dockprom_service



- name: Launch prometheus & grafana
  #command: docker-compose -f ./docker-compose.prometheus.host-net.yml up -d --build --force-recreate
  command: docker-compose -f ./docker-compose.prometheus.host-net.yml up -d --build
  args:
    chdir: /home/{{ user_name }}/d_service
  tags: dockprom_service



- name: Install dashboards
  include: dashboards.yml
  tags: dockprom_service

