---

- name: Checkout repo
  git:
    repo: 'https://github.com/donDonald/dockprom.git'
    dest: /home/{{ user_name }}/d_service
    version: 4c2b86c47c31b011ca490560615fc7eff875bf96
  tags: dockprom_service



- name: git checkout to proper version
  command: git checkout --track origin/movi9ng-to-host-hetwork-mode
  args:
    chdir: /home/{{ user_name }}/d_service
  tags: dockprom_service




- name: Deploy prometheus config
  template:
    src: prometheus/prometheus.yml
    dest: /home/{{ user_name }}/d_service/prometheus/prometheus.yml
  tags: dockprom_service




- name: Deploy grafana config
  template:
    src: grafana/provisioning/datasources/datasource.yml
    dest: /home/{{ user_name }}/d_service/grafana/provisioning/datasources/datasource.yml
  tags: dockprom_service




- name: Launch prometheus & grafana
  command: docker-compose -f ./docker-compose.prometheus.host-net.yml up -d --build --force-recreate
  args:
    chdir: /home/{{ user_name }}/d_service
  tags: dockprom_service

