---

- name: Checkout repo
  git:
    repo: 'https://github.com/donDonald/dockprom.git'
    force: true
    dest: /home/{{ user_name }}/d_service
    version: '{{ version }}'
  tags: dockprom_service



- name: Deploy prometheus config
  template:
    src: prometheus/prometheus.yml
    dest: /home/{{ user_name }}/d_service/prometheus/prometheus.yml
  tags: dockprom_service



- name: Deploy grafana config
  template:
    src: grafana/provisioning/datasources/datasource.yml
    dest: /home/{{ user_name }}/d_service/grafana/provisioning/datasources/datasource.yml
  tags: dockprom_service



- name: Deploy grafana 11074.node-exporter-for-prometheus-dashboard-en-v20201010_rev9.json dashboard
  copy:
    src: grafana/provisioning/dashboards/11074.json
    dest: /home/{{ user_name }}/d_service/grafana/provisioning/dashboards/11074.node-exporter-for-prometheus-dashboard-en-v20201010_rev9.json
    #dest: /home/{{ user_name }}/11074.node-exporter-for-prometheus-dashboard-en-v20201010_rev9.json
  tags: dockprom_service



- name: Deploy grafana 1860.node-exporter-full_rev21.json dashboard
  copy:
    src: grafana/provisioning/dashboards/1860.json
    dest: /home/{{ user_name }}/d_service/grafana/provisioning/dashboards/1860.node-exporter-full_rev21.json
    #dest: /home/{{ user_name }}/1860.node-exporter-full_rev21.json
  tags: dockprom_service



- name: Deploy grafana 10180.kds-linux-hosts_rev1.json dashboard
  copy:
    src: grafana/provisioning/dashboards/10180.json
    dest: /home/{{ user_name }}/d_service/grafana/provisioning/dashboards/10180.kds-linux-hosts_rev1.json
    #dest: /home/{{ user_name }}/10180.kds-linux-hosts_rev1.json
  tags: dockprom_service



- name: Launch prometheus & grafana
  command: docker-compose -f ./docker-compose.prometheus.host-net.yml up -d --build --force-recreate
  args:
    chdir: /home/{{ user_name }}/d_service
  tags: dockprom_service

