---

#https://portainer.readthedocs.io/en/stable/deployment.html#inside-a-swarm-cluster
#https://portainer.readthedocs.io/en/stable/agent.html

- name: Print out portainer info
  debug:
    msg:
     - "tag: {{ portainer.tag }}"
     - "src_port: {{ portainer.src_port }}"
     - "dst_port: {{ portainer.dst_port }}"
  tags: portainer



- name: Copy portainer deployment file
  vars:
    tag: '{{ portainer.tag }}'
    src_port: '{{ portainer.src_port }}'
    dst_port: '{{ portainer.dst_port }}'
  template:
    src: 'portainer-stack.j2'
    dest: '/tmp/portainer-stack.yml'
  tags: portainer

 

- name: Deploy portainer
  command: docker stack deploy --compose-file=/tmp/portainer-stack.yml portainer
  tags: portainer

