# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
    {
        :hostname => "h1",
        :ip => "192.168.200.10",
        :box => "generic/ubuntu2004",
        :ram => 2048,
        :cpu => 1,
        :ports => [
            {   # portainer
                :host => 9000,
                :guest => 9000,
            },
            {   # pagdmin
                :host => 11111,
                :guest => 11111,
            },
            {   # dockprom.grafana
                :host => 3000,
                :guest => 3000,
            },
            {   # dockprom.alertmanager
                :host => 9093,
                :guest => 9093,
            },
            {   # dockprom.prometheus
                :host => 9090,
                :guest => 9090,
            },
            {   # dockprom.node-exporter
                :host => 9100,
                :guest => 9100,
            }
        ]
    },
    {
        :hostname => "h2",
        :ip => "192.168.200.100",
        :box => "generic/ubuntu2004",
        :ram => 2048,
        :cpu => 1,
        :ports => [
        ]
    }
]

Vagrant.configure("2") do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
            # forward ports
            machine[:ports].each do |ports|
                node.vm.network "forwarded_port", guest:ports[:guest], host:ports[:host]
            end
        end
    end
end
