---
# ansible-playbook -i hosts -K main.yml

- name: Basic setup
  hosts: all
  roles:
    - devtools



- name: DNS servers setup
  hosts: dns_servers
  roles:
    - dns



- name: DNS clients setup
  hosts: dns_clients
  roles:
    - dns_client



- name: Setup portainer as swarm
  import_playbook: portainer.yml



####- name: Db servers setup
####  hosts: db_servers
####  roles:
####    - docker_v2
####    - docker_compose_v2
####    - postgres



####- name: Swarm managers setup
####  hosts: swarm_managers
####  roles:
####    - python3
####    - docker_v2
####    - docker_swarm_manager



####- name: Swarm workers setup
####  hosts: swarm_workers
####  roles:
####    - python3
####    - docker_v2
####    - docker_swarm_worker



####- name: App servers setup
####  hosts: app_servers
####  roles:
####    - docker_swarm_service



####- name: Setup cAdvisor
####  hosts: cadvisor
####  roles:
####    - cadvisor



####- name: Setup monitoring
####  hosts: monitoring
####  roles:
####    - dockprom

