---

- name: Setup portainer swarm manager
  hosts: PORTAINER
  roles:
    - python3
    - docker_v2
    - docker_compose_v2
    - docker_swarm_manager



- name: Setup portainer swarm workers(agents)
  hosts: PORTAINER_AGENTS
  vars:
    manager_group: 'PORTAINER'
  roles:
    - python3
    - docker_v2
    - docker_compose_v2
    - docker_swarm_worker



- name: Deploy portainer
  hosts: PORTAINER
  roles:
    - python3
    - docker_v2
    - docker_compose_v2
    - portainer_service

