version: '3.2'



networks:
    xyzzz:
        driver: overlay



services:



    example1:
        image: dondonald/devops-example1:latest
        restart: always
        ports:
            - '3000:3000'
        networks:
            - xyzzz
        deploy:
            mode: replicated
            replicas: 2
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 128M

