---

#https://docs.ansible.com/ansible/latest/modules/docker_swarm_module.html
#https://docs.ansible.com/ansible/latest/modules/docker_swarm_info_module.html
#https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html
#https://github.com/ruanbekker/ansible-docker-swarm/blob/master/roles/docker-swarm-init/tasks/main.yml

- name: Check if Swarm has already been initialized
  shell: docker info
  register: swarm_info
  ignore_errors: true
  changed_when: False # Never changes the machine
  tags: docker-swarm-manager



- debug:
    msg:
      - "Swarm is initialized:{{ swarm_info.stdout.find('Swarm: inactive') == -1 }}"
      - "docker api version:'{{ docker.api_version }}"
  tags: docker-swarm-manager



- name: Init a new swarm
  docker_swarm:
    api_version: '{{ docker.api_version }}'
    state: present
    advertise_addr: '{{ docker_swarm_manager.advertise_address }}'
# when: not swarm_info.docker_swarm_active # Only in case the swarm is not initialized
  when: "swarm_info.stdout.find('Swarm: inactive') != -1" # Only in case the swarm is not initialized
  tags: docker-swarm-manager



- name: Get info on Docker Swarm
  docker_swarm_info:
    api_version: '{{ docker.api_version }}'
# ignore_errors: yes
  register: swarm_info_2
  tags: docker-swarm-manager



- include: network.yml



- debug:
    msg:
      - "inventory_hostname:{{ inventory_hostname }}"
      - "advertise_address:{{ docker_swarm_manager.advertise_address }}"
      - 'Docker in Swarm mode:{{ swarm_info_2.docker_swarm_active }}'
      - 'This is a Manager node:{{ swarm_info_2.docker_swarm_manager }}'
      - 'Manager token:{{ swarm_info_2.swarm_facts.JoinTokens.Manager }}'
      - 'Worker token:{{ swarm_info_2.swarm_facts.JoinTokens.Worker }}'
  tags: docker-swarm-manager

