version: '3.2'



services:

    server:
        image: dregistry:5000/server:latest
        ports:
            - "3000:3000"
        volumes:
            - /var/example1:/var/example1:rw
            - /etc/hostname:/etc/host_hostname:ro

    exporter:
        image: dregistry:5000/exporter:latest
        ports:
            - "3001:3001"
        volumes:
            - /var/example1:/var/example1:ro

