---

- name: Install docker-compose
  become: true
  become_method: sudo
  become_user: root
  remote_user: '{{ user_name }}'
  script: docker.compose.install.sh
  args:
    executable: bash
    state: present
  tags: docker_compose



# Have to reset to handle group changes
- name: Reset ssh connection
  meta: reset_connection

